### ISSUE TITLE
Translate : Add New more Languages 🇩🇿 🇧🇷 🇻🇳 🇮🇩 🇨🇳 🇦🇱 🇯🇵

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#643]
Add New more missed Languages  , check video below : 

 **please add new pr for each language**

[https://www.youtube.com/watch?v=CbqGqOObniQ](https://www.youtube.com/watch?v=CbqGqOObniQ)

- [x] Add #663 Language in React.js App
- [x] #667
- [x] #680
- [x] #675
- [x] #672
- [x] #673
- [x] #674
- [x] #684
- [x] #687
- [x] Add 🇮🇳 Hindi Language in React.js App
- [x] Add #665 Language in React.js App
- [x] Add #666 Language in React.js App
- [x] #668
- [x] #669
- [x] #670
- [x] #671
- [x] Add 🇩🇪 German  Language in React.js App
- [x] #676
- [x] #677
- [x] Add #664 Language in React.js App
- [x] #678
- [x] #679
- [x] #681
- [x] #682
- [x] #683
- [x] #685
- [x] Add 🇧🇷 Portuguese (Brazil)  Language in React.js App
- [x] #686
- [x] Add 🇷🇺 Russian  Language in React.js App
- [x] #688
- [x] #689
- [x] Add 🇪🇸 Spanish  Language in React.js App
- [x] #690
- [x] #691
- [x] Add 🇹🇭 Thai  Language in React.js App
- [x] Add 🇹🇷 Turkish  Language in React.js App
- [x] #692
- [x] #693
- [x] #694

**Comment by shruti-1104** [comment]
@salahlalami Can you please assign this issue to me?

**Comment by salahlalami** [comment]
@shruti-1104 Sure , you can work on it , please add new pr for each language
